# Generated by Django 3.0.2 on 2020-01-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
